config/routes.rb
InTest::Application.routes.draw do

  

  

 

  resources :tests

  resources :main

  get "welcome/index"

  root 'welcome#index'
 
  get 'results/all_results' => 'results#all_results' 

  post 'questions/save_all' => 'questions#save_all' 
  get 'questions/delete_all' => 'questions#delete_all'   

  post 'questions/formQuestions' => 'questions#formQuestions' 
  post 'questions/form_answers' => 'questions#form_answers' 

  post 'results/save_all' => 'results#save_all' 
  get 'users/show_result' => 'users#show_result' 
  

  post 'scales/save_all' => 'scales#save_all' 
  get  'scales/delete_all' => 'scales#delete_all'   
 
  post 'interpretations/save_all_inters' => 'interpretations#save_all_inters' 
  get  'interpretations/delete_all_inters' => 'interpretations#delete_all_inters'    
 
 resources :results

  resources :questions

  resources :users

  resources :answers   

  resources :interpretations

  resources :scale_results

  resources :scales  
         

  

end

app/models/question.rb
class Question < ActiveRecord::Base
	belongs_to :test
	has_many   :answers	, :dependent => :delete_all
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :require_login


  def require_login
      ck = cookies[:admin]
      if ck!=User.find(1).cookie
         render nothing: true, status: :unauthorized
      end
  end

  # GET /questions
  # GET /questions.json
  def index
		if params[:test] == nil
		   @questions = Question.all 
	    else
	      @test_id   = params[:test]
        @test      = Test.find(@test_id)
	   		@questions = Question.where(test_id: params[:test])	    	
	   		@question  = Question.new 

     		if @questions[0]==nil
          @questions[0] = Question.create
	   			@questions[0].test_id = @test_id
	   		end

	   		@test_name = @questions[0].test.name
	   		@answer = Answer.new 
       end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  	respond_to do |format|
        format.html
        format.js {head :no_content }  
        format.json { render  'show' }
    end
  end

  # GET /questions/new
  def new
    @question = Question.create
    
    @question.test_id = params[:test_id]
    @question.save
    
    
    
    respond_to do |format|
    format.html { } # in the case of disabled JS support
    format.js
  end

  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

	def save_all
		params["questions"].each() do |(key,value)|
        	@question=Question.find(key)
        	if(@question!=nil)
	        	@question.update(value)
        	end	
		end
    	params["answers"].each do |(key,value)| 
	        @answer=Answer.find(key)
        	@answer.update(value)
    	end
   
	end

  	def delete_all
		@test_id = params["test_id"]
		Question.delete_all(:test_id => @test_id)
		Answer.delete_all(:test_id => @test_id)
 		respond_to do |format|
	        format.html { }
        	format.js { head :no_content }
    	end		

	end
    
   
  
  def formQuestions
    test= Test.find(params["test_id"])
    
    delete_all()
    if test.test_type==2 
       qtext2 = params["question_text2"].split("\n")
       i=0
    end   
	  params["question_names"].split("\n").each do |value|
         q = Question.new()
         q.text = value
         q.test_id = params["test_id"]
         if test.test_type==2 
            q.text2   = qtext2[i]
            i=i+1
         end   
         q.save
      end
  end  
  
  def form_answers
    
    Answer.delete_all(:test_id => params["test_id"])
     qs = Question.where(test_id: params["test_id"])
     qs_values = params["answer_values"].split("\n") 
     qs.each do |q|
      i=0
       params["answer_names"].split("\n") .each do |value|
         a = Answer.new()
         a.text          = value
         a.answer_value = qs_values[i]
         a.test_id 	     = params["test_id"]
         a.question_id   = q.id
         a.save	         
         i += 1
    end    
  end
  end  
  

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.js { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text, :test_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :test_id %><br>
    <%= f.number_field :test_id %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/questions/_new.html.erb
<div class="question-block" id="<%=@question.id %>">
	<div class="input-prepend input-append">
		<span class='add-on'><i class='icon-resize-vertical'></i></span>
		     
		     <%= fields_for 'questions[]', @question do |qf| %>
		         <%= qf.text_field :text, :class => 'input-q' %>
		     <% end %> 
       <%= link_to 'X', @question, method: :delete, class:'btn delete-q', remote: true  %>         
	</div>
	<div class="answer-block" id=>
	<%= link_to 'Добавить ответ',new_answer_path(:test_id => @test_id,:question_id => @question.id), class:'btn btn-small',id: 'add-a', remote: true %>
	</div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/formQuestions.html.erb
<%=  %>

app/views/questions/form_answers.html.erb
<%= @p %>

app/views/questions/index.html.erb
<h1><%= @test_name %></h1>

 

<%= form_for @question, remote: true, url: {action: "formQuestions"} do |form| %>
	<input type='text' name="test_id" value="<%= @test_id %>" style="display:none"></div>
	<%= text_area_tag(:question_names, "", rows: 5)  %>	
	<% if @test.test_type==2 %>
		<%= text_area_tag(:question_text2, "", rows: 5)  %>	
	<% end %>	
	<%= submit_tag("Сформировать вопросы",class:'btn btn-small') %>   
<% end %>




<%= form_for @answer, remote: true, url: {action: "form_answers"} do |form| %>
	<input type='text' name="test_id" value="<%= @test_id %>" style="display:none"></div>
	<%= text_area_tag(:answer_names, "", rows: 5, cols: 30,class: 'answer')  %>	
	<%= text_area_tag(:answer_values, "", rows: 5, cols: 30,class: 'answer')  %>	
	<%= submit_tag("Сформировать ответы",class:'btn btn-small') %>   
<% end %>

<%= form_for @question, remote: true, url: {action: "save_all"} do |f| %>
	<% @questions.each do |question| %>
		<%= fields_for 'questions[]', question do |qf| %>
    	<div class="question-block" id="<%=question.id %>">
      		<div class="input-prepend input-append">
         		<span class='add-on'>       		
         		<i class='icon-resize-vertical'></i>
         		</span>
		     	<%= qf.text_field :text, :class => 'input-q'%>
       			<%= link_to 'X', question, method: :delete, class:'btn delete-q', remote: true  %>         
      		</div>

      		<div class="answer-block">
		    	<% question.answers.each do |answer| %>
			       <%= fields_for 'answers[]',answer do |af| %>	
					 <div class="one-answer input-append">
     			   		<%= af.text_field :text %>
     			   		<%= af.text_field :answer_value %>
						<%= link_to 'X', answer, method: :delete, class:'btn delete-a', remote: true  %>              			   		
					  </div>
             		  <br>
  			 		<% end %>
		  		<% end %>
	    	    <%= link_to 'Добавить ответ',new_answer_path(:test_id => @test_id,:question_id => question.id), class:'btn btn-small',id: 'add-a', remote: true %>
			</div>
      		<br>
		</div>
		<% end %>
	<% end %>
	<br>	
	<%= link_to 'Добавить вопрос', new_question_path(:test_id => @test_id), class:'btn btn-small',id: 'add-q', remote: true %>
	<%= submit_tag("Сохранить",class:'btn btn-small',id:'submit-button') %>
	<%= link_to 'Удалить все', {controller: 'questions', action: 'delete_all',:test_id => @test_id}, class:'btn btn-small',remote: true %>
	<div id='end-body'></div>
<% end %>

app/views/questions/new.html.erb
<div class="question-block" id='new-q'>
	<div class="input-prepend input-append">
		<span class='add-on'><i class='icon-resize-vertical'></i></span>
		     
		     <%= fields_for 'questions[]', @question do |qf| %>
		         <%= qf.text_field :text, :class => 'input-q' %>
		     <% end %> 
       <%= link_to 'X', @question, method: :delete, class:'btn delete-q', remote: true  %>         
	</div>
	<div class="answers-block">
	</div>
</div>

app/views/questions/new.js.erb
$(".question-block").last().after("<%= escape_javascript(render partial: 'new' ) %>"); 

$('body').animate({scrollTop: $('#end-body').position().top+20},1000);

app/views/questions/save_all.html.erb
<%= @test_id.to_s+" ttt" %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<p>
  <strong>Test:</strong>
  <%= @question.test_id %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>