config/routes.rb
InTest::Application.routes.draw do

  

  

 

  resources :tests

  resources :main

  get "welcome/index"

  root 'welcome#index'
 
  get 'results/all_results' => 'results#all_results' 

  post 'questions/save_all' => 'questions#save_all' 
  get 'questions/delete_all' => 'questions#delete_all'   

  post 'questions/formQuestions' => 'questions#formQuestions' 
  post 'questions/form_answers' => 'questions#form_answers' 

  post 'results/save_all' => 'results#save_all' 
  get 'users/show_result' => 'users#show_result' 
  

  post 'scales/save_all' => 'scales#save_all' 
  get  'scales/delete_all' => 'scales#delete_all'   
 
  post 'interpretations/save_all_inters' => 'interpretations#save_all_inters' 
  get  'interpretations/delete_all_inters' => 'interpretations#delete_all_inters'    
 
 resources :results

  resources :questions

  resources :users

  resources :answers   

  resources :interpretations

  resources :scale_results

  resources :scales  
         

  

end

app/models/scale_result.rb
class ScaleResult < ActiveRecord::Base
end

app/controllers/scale_results_controller.rb
class ScaleResultsController < ApplicationController
  before_action :set_scale_result, only: [:show, :edit, :update, :destroy]
  before_action :require_login


  def require_login
      ck = cookies[:admin]
      if ck!=User.find(1).cookie
         render nothing: true, status: :unauthorized
      end
  end
  # GET /scale_results
  # GET /scale_results.json
  def index
    @scale_results = ScaleResult.all
  end

  # GET /scale_results/1
  # GET /scale_results/1.json
  def show
  end

  # GET /scale_results/new
  def new
    @scale_result = ScaleResult.new
  end

  # GET /scale_results/1/edit
  def edit
  end

  # POST /scale_results
  # POST /scale_results.json
  def create
    @scale_result = ScaleResult.new(scale_result_params)

    respond_to do |format|
      if @scale_result.save
        format.html { redirect_to @scale_result, notice: 'Scale result was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scale_result }
      else
        format.html { render action: 'new' }
        format.json { render json: @scale_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scale_results/1
  # PATCH/PUT /scale_results/1.json
  def update
    respond_to do |format|
      if @scale_result.update(scale_result_params)
        format.html { redirect_to @scale_result, notice: 'Scale result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scale_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scale_results/1
  # DELETE /scale_results/1.json
  def destroy
    @scale_result.destroy
    respond_to do |format|
      format.html { redirect_to scale_results_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scale_result
      @scale_result = ScaleResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scale_result_params
      params.require(:scale_result).permit(:scale_id, :user_id, :result)
    end
end

app/helpers/scale_results_helper.rb
module ScaleResultsHelper
end

app/views/scale_results/_form.html.erb
<%= form_for(@scale_result) do |f| %>
  <% if @scale_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scale_result.errors.count, "error") %> prohibited this scale_result from being saved:</h2>

      <ul>
      <% @scale_result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :scale_id %><br>
    <%= f.number_field :scale_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.number_field :result %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scale_results/edit.html.erb
<h1>Editing scale_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @scale_result %> |
<%= link_to 'Back', scale_results_path %>

app/views/scale_results/index.html.erb
<h1>Listing scale_results</h1>

<table>
  <thead>
    <tr>
      <th>Scale</th>
      <th>User</th>
      <th>Result</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scale_results.each do |scale_result| %>
      <tr>
        <td><%= scale_result.scale_id %></td>
        <td><%= scale_result.user_id %></td>
        <td><%= scale_result.result %></td>
        <td><%= link_to 'Show', scale_result %></td>
        <td><%= link_to 'Edit', edit_scale_result_path(scale_result) %></td>
        <td><%= link_to 'Destroy', scale_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scale result', new_scale_result_path %>

app/views/scale_results/new.html.erb
<h1>New scale_result</h1>

<%= render 'form' %>

<%= link_to 'Back', scale_results_path %>

app/views/scale_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Scale:</strong>
  <%= @scale_result.scale_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @scale_result.user_id %>
</p>

<p>
  <strong>Result:</strong>
  <%= @scale_result.result %>
</p>

<%= link_to 'Edit', edit_scale_result_path(@scale_result) %> |
<%= link_to 'Back', scale_results_path %>