config/routes.rb
InTest::Application.routes.draw do

  

  

 

  resources :tests

  resources :main

  get "welcome/index"

  root 'welcome#index'
 
  get 'results/all_results' => 'results#all_results' 

  post 'questions/save_all' => 'questions#save_all' 
  get 'questions/delete_all' => 'questions#delete_all'   

  post 'questions/formQuestions' => 'questions#formQuestions' 
  post 'questions/form_answers' => 'questions#form_answers' 

  post 'results/save_all' => 'results#save_all' 
  get 'users/show_result' => 'users#show_result' 
  

  post 'scales/save_all' => 'scales#save_all' 
  get  'scales/delete_all' => 'scales#delete_all'   
 
  post 'interpretations/save_all_inters' => 'interpretations#save_all_inters' 
  get  'interpretations/delete_all_inters' => 'interpretations#delete_all_inters'    
 
 resources :results

  resources :questions

  resources :users

  resources :answers   

  resources :interpretations

  resources :scale_results

  resources :scales  
         

  

end

app/models/scale.rb
class Scale < ActiveRecord::Base
	belongs_to :test
end

app/controllers/scales_controller.rb
class ScalesController < ApplicationController
  before_action :set_scale, only: [:show, :edit, :update, :destroy]
  before_action :require_login


  def require_login
      ck = cookies[:admin]
      if ck!=User.find(1).cookie
         render nothing: true, status: :unauthorized
      end
  end
  # GET /scales
  # GET /scales.json
  def index
    if params[:test] == nil
        @scales = Scale.all
    else
        @test_id   = params[:test]
        @test      = Test.find(@test_id)
        @scales = Scale.where(test_id: params[:test])       
        @scale  = Scale.new
        @scale_for_user = @test.scales.where(for_user: 't')
        @scale_for_user_id= @scale_for_user[0].id if @scale_for_user[0]!=nil 
        @interpretations = Interpretation.where(scale_id: @scale_for_user)       
        @interpretation  = Interpretation.new 

        

        @test_name = @test.name
    end
  end

  # GET /scales/1
  # GET /scales/1.json
  def show
  end

  # GET /scales/new
  def new
     @scale = Scale.create
     @scale.test_id = params[:test_id]
     @scale.save
     respond_to do |format|
        format.html { } # in the case of disabled JS support
        format.js
    end    
  end

  # GET /scales/1/edit
  def edit
  end

  # POST /scales
  # POST /scales.json
  def create
    @scale = Scale.new(scale_params)

    respond_to do |format|
      if @scale.save
        format.html { redirect_to @scale, notice: 'Scale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scale }
      else
        format.html { render action: 'new' }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scales/1
  # PATCH/PUT /scales/1.json
  def update
    respond_to do |format|
      if @scale.update(scale_params)
        format.html { redirect_to @scale, notice: 'Scale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scales/1
  # DELETE /scales/1.json
  def destroy
    @scale.destroy
    respond_to do |format|
      format.html { redirect_to scales_url }
      format.json { head :no_content }
      format.js { head :no_content }      
    end
  end


  def delete_all
    @test_id = params["test_id"]
    Scale.delete_all(:test_id => @test_id)
    respond_to do |format|
          format.html { }
          format.js { head :no_content }
      end   

  end

  def save_all
    params["scales"].each() do |(key,value)|
          @scale=Scale.find(key)
          if(@scale!=nil)
            @scale.update(value)
          end 
          if @scale.for_user='t'
             @scale_for_user_id=@scale.id
          end  
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scale
      @scale = Scale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scale_params
      params.require(:scale).permit(:test_id, :name, :questions, :result, :for_user)
    end
end

app/helpers/scales_helper.rb
module ScalesHelper
end

app/views/scales/_form.html.erb
<%= form_for(@scale) do |f| %>
  <% if @scale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scale.errors.count, "error") %> prohibited this scale from being saved:</h2>

      <ul>
      <% @scale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :test_id %><br>
    <%= f.number_field :test_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :questions %><br>
    <%= f.text_field :questions %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.number_field :result %>
  </div>
  <div class="field">
    <%= f.label :for_user %><br>
    <%= f.check_box :for_user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scales/_new.html.erb
<div class="input-append one-scale">
   <%= fields_for 'scales[]',@scale do |af| %>	
           <%= af.check_box(:for_user) %>
     	<%= af.text_field :name %>
     	<%= af.text_field :questions %>
  	<% end %>
	<%= link_to 'X', @scale, method: :delete, class:'btn delete-a', remote: true  %>              			   		
</div>	

app/views/scales/edit.html.erb
<h1>Editing scale</h1>

<%= render 'form' %>

<%= link_to 'Show', @scale %> |
<%= link_to 'Back', scales_path %>

app/views/scales/index.html.erb
<h1><%= @test_name %></h1>
 <h4>Шкалы</h4>
<%= form_for @scale, remote: true, url: {action: "save_all"} do |f| %>
 <div class="one-scale input-append">
 </div> 
  <% @scales.each do |scale| %>
     <%= fields_for 'scales[]',scale do |sf| %> 
        <div class="one-scale input-append">

        <%= sf.check_box(:for_user) %>
        <%= sf.text_field :name %>
        <%= sf.text_field :questions %>
        <%= link_to 'X', scale, method: :delete, class:'btn delete-a', remote: true  %>                          
        </div>
      <% end %>
 
  <% end %>
  <%= link_to 'Добавить шкалу',new_scale_path(:test_id => @test_id), class:'btn btn-small',id: 'add-s', remote: true %>
  <%= submit_tag("Сохранить",class:'btn btn-small',id:'submit-button') %>
  <%= link_to 'Удалить все', {controller: 'scales', action: 'delete_all',:test_id => @test_id}, class:'btn btn-small',remote: true %>
<% end %>
<div id='end-body'></div>
<br>
<br>
 <h4>Интерпертации</h4>
<%= form_for @interpretation, remote: true, url: {controller: 'interpretations',action: "save_all_inters"} do |f| %>
 <div class="one-interpretation input-append">
 </div> 
  <% @interpretations.each do |interpretation| %>
     <%= fields_for 'interpretations[]',interpretation do |sf| %> 
        <div class="one-interpretation input-append">
        <%= sf.number_field :value_from, class: 'intervals' %>
        <%= sf.number_field :value_to, class: 'intervals' %>
        <%= sf.text_area :text, cols: 100, rows: 5, class: 'text_i' %>
        <%= link_to 'X', interpretation, method: :delete, class:'btn delete-a', remote: true  %>                          
        </div>
      <% end %>
 
  <% end %>
  <%= link_to 'Добавить',new_interpretation_path(:scale_id => @scale_for_user_id), class:'btn btn-small',id: 'add-int', remote: true %>
  <%= submit_tag("Сохранить",class:'btn btn-small',id:'submit-button') %>
  <%= link_to 'Удалить все', {controller: 'interpretations', action: 'delete_all_inters',:scale_id => @scale_id}, class:'btn btn-small',remote: true %>
<% end %>

app/views/scales/new.html.erb
<h1>New scale</h1>

<%= render 'form' %>

<%= link_to 'Back', scales_path %>

app/views/scales/new.js.erb
var ans_bl = $(".one-scale");
if ($(ans_bl).html()!=null)
{

	$(ans_bl).last().after("<%= escape_javascript(render partial: 'new' ) %>");
}
else
{
    $(ans_bl).prepend("<%= escape_javascript(render partial: 'new' ) %>");	
}

app/views/scales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Test:</strong>
  <%= @scale.test_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @scale.name %>
</p>

<p>
  <strong>Questions:</strong>
  <%= @scale.questions %>
</p>

<p>
  <strong>Result:</strong>
  <%= @scale.result %>
</p>

<p>
  <strong>For user:</strong>
  <%= @scale.for_user %>
</p>

<%= link_to 'Edit', edit_scale_path(@scale) %> |
<%= link_to 'Back', scales_path %>