config/routes.rb
InTest::Application.routes.draw do

  

  

 

  resources :tests

  resources :main

  get "welcome/index"

  root 'welcome#index'
 
  get 'results/all_results' => 'results#all_results' 

  post 'questions/save_all' => 'questions#save_all' 
  get 'questions/delete_all' => 'questions#delete_all'   

  post 'questions/formQuestions' => 'questions#formQuestions' 
  post 'questions/form_answers' => 'questions#form_answers' 

  post 'results/save_all' => 'results#save_all' 
  get 'users/show_result' => 'users#show_result' 
  

  post 'scales/save_all' => 'scales#save_all' 
  get  'scales/delete_all' => 'scales#delete_all'   
 
  post 'interpretations/save_all_inters' => 'interpretations#save_all_inters' 
  get  'interpretations/delete_all_inters' => 'interpretations#delete_all_inters'    
 
 resources :results

  resources :questions

  resources :users

  resources :answers   

  resources :interpretations

  resources :scale_results

  resources :scales  
         

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
 	belongs_to :question
	belongs_to :test	
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]
  before_action :require_login


  def require_login
      ck = cookies[:admin]
      if ck!=User.find(1).cookie
         render nothing: true, status: :unauthorized
      end
  end

  # GET /answers
  # GET /answers.json
  def index
       if params[:test] == nil
	  	   @answers = Answer.all 
	    else
   		   @answers = Answer.where(test_id: params[:test]).order(:question_id)	    	
         @answers.each do |answer|
           @ques = answer.question
        end  
       end
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.create
    @answer.test_id = params[:test_id]
    @answer.question_id = params[:question_id]
    @answer.save

    respond_to do |format|
        format.js 
    end    
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = Answer.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @answer, notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { render action: 'new' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
      
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.js { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:text, :answer_value, :test_id, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :answer_value %><br>
    <%= f.number_field :answer_value %>
  </div>
  <div class="field">
    <%= f.label :test_id %><br>
    <%= f.number_field :test_id %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/_new.html.erb
<div class="input-append one-answer">
   <%= fields_for 'answers[]',@answer do |af| %>	
     	<%= af.text_field :text %>
     	<%= af.text_field :answer_value %>
  	<% end %>
	<%= link_to 'X', @answer, method: :delete, class:'btn delete-a', remote: true  %>              			   		
</div>	

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Answer value</th>
      <th>Test</th>
      <th>Question</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= qid=0 %>

    <% @answers.each do |answer| %>
       
     
       
      
      <tr>
      <td><%=  answer.question.text if answer.question_id!=qid  %></td>
      <%= qid=answer.question_id %>
        <td><%= answer.text %></td>
        <td><%= answer.answer_value %></td>
        <td><%= answer.test_id %></td>
        <td><%= answer.question_id %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <tr></tr>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path, remote: true %>
<div id='answer-new'></div>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/new.js.erb
var question_id = <%= params[:question_id] %>;
var ans_bl = $("#"+question_id+".question-block").find(".answer-block");
if ($(ans_bl).find(".input-append").html()!=null)
{
	$(ans_bl).find(".input-append").last().after("<%= escape_javascript(render partial: 'new' ) %>");
}
else
{
    $(ans_bl).prepend("<%= escape_javascript(render partial: 'new' ) %>");	
}

//console.log($(ans_bl).find('input:last').position().top);
//$('body').animate({scrollTop: $(ans_bl).find('input:last').position().top+10},100);

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @answer.text %>
</p>

<p>
  <strong>Answer value:</strong>
  <%= @answer.answer_value %>
</p>

<p>
  <strong>Test:</strong>
  <%= @answer.test_id %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>